import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/user/entities/user.entity';

export class LoginResponseDto {
  @ApiProperty({
    description: 'JWT generated by login',
    example: '5465d4sa.d5sd6s456a.56ds156das',
  })
  token: string;

  @ApiProperty({
    description: 'User data',
  })
  user: User;
}
